use_artifact = true
artifact_owner = "cem5113"
artifact_repo = "crime_prediction_data"
artifact_name = "sf-crime-parquet"

geojson_owner = "cem5113"
geojson_repo  = "crimepredict"
geojson_path  = "data/sf_cells.geojson"
